set schema addressbookuser;

create table address(
    id                      int generated by default as identity not null,
    city                    varchar(255) not null,
    state                   varchar(255) not null,
    street_address          varchar(255) not null,
    zipcode                 varchar(255) not null,
    primary key(id)
);

create table phone(
    id                      int generated by default as identity not null,
    number                  varchar(255) not null,
    primary key(id)
);

create table company(
    id                      int generated by default as identity not null,
    name                    varchar(255) not null,
    primary key(id)
);

create table department(
    id                      int generated by default as identity not null,
    name                    varchar(255) not null,
    company_id              int not null,
    primary key(id),
    foreign key(company_id) references company(id)
);

create table employee(
    id                      int generated by default as identity not null,
    first_name              varchar(255) not null,
    last_name               varchar(255) not null,
    department_id           int not null,
    primary key(id),
    foreign key(department_id) references department(id)
);

create table company_address(
    company_id              int not null,
    address_id              int not null,
    foreign key(company_id) references company(id),
    foreign key(address_id) references address(id)
);

create table company_phone(
    company_id              int not null,
    phone_id                int not null,
    foreign key(company_id) references company(id),
    foreign key(phone_id) references phone(id)
);

create table employee_address(
    employee_id             int not null,
    address_id              int not null,
    foreign key(employee_id) references employee(id),
    foreign key(address_id) references address(id)
);

create table employee_phone(
    employee_id             int not null,
    phone_id                int not null,
    foreign key(employee_id) references employee(id),
    foreign key(phone_id) references phone(id)
);
